# ISO 639-1 codes of supported languages
languages: [
              ['Arabic', 'ar'],
              ['Chinese', 'zh'],
              ['English', 'en'],
              ['French', 'fr'],
              ['German', 'de'],
              ['Lingala', 'ln'],
              ['Portuguese', 'pt'],
              ['Spanish', 'es'],
              ['Swahili', 'sw']
          ]
page_tags: ['About', 'External Links']
exception_notifications:
  email_prefix: '[Hel\LO Project] '
  sender: 'dranoel.bravo@gmail.com'
  recipients: ['dranoel.bravo@gmail.com']